//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_mechanic.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanic
    {
        public Mechanic()
        {
            this.Mechanic_Service = new HashSet<Mechanic_Service>();
            this.Holiday = new HashSet<Holiday>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int FranchiseID { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual ICollection<Mechanic_Service> Mechanic_Service { get; set; }
        public virtual ICollection<Holiday> Holiday { get; set; }
    }
}
